language: haskell
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.stack
before_install:
  - mkdir -p ~/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xz -C ~/bin --wildcards '*/stack' --strip-components=1
  - chmod -R a+x ~/bin
install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal
script:
  - stack test --no-terminal
