language: haskell
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.stack
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal
script:
  - stack test --no-terminal
